[profile.default]
src = 'src'
test = 'src/test'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]
solc = '0.8.17'
remappings = [
    'src/=src/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config